package orchestration

import (
	"fmt"

	"github.com/iSundram/WhyMailAi/pkg/types"
)

// RouteResult is the output from the orchestration layer.
type RouteResult struct {
	Result       any
	Confidence   float64
	Explanations []string
	SafetyFlags  []string
}

// Router routes requests by task type to model pipelines.
type Router struct{}

// NewRouter creates a routing instance.
func NewRouter() *Router {
	return &Router{}
}

// Run executes baseline routing logic.
func (r *Router) Run(taskType types.TaskType, input map[string]any) RouteResult {
	_ = input
	switch taskType {
	case types.TaskSpamClassification:
		return RouteResult{Result: map[string]any{"label": "ham", "recommended_action": "allow"}, Confidence: 0.95, Explanations: []string{"baseline lexical model"}}
	case types.TaskPhishingClassify:
		return RouteResult{Result: map[string]any{"label": "legitimate", "recommended_action": "allow"}, Confidence: 0.93, Explanations: []string{"sender and URL risk low"}}
	case types.TaskEmailDrafting:
		return RouteResult{Result: map[string]any{"draft": "Thanks for your email. I'll review this and follow up shortly."}, Confidence: 0.90, Explanations: []string{"baseline drafting assistant"}}
	case types.TaskEmailRewrite:
		return RouteResult{Result: map[string]any{"rewrite": "Thank you for your message. I will review and respond soon."}, Confidence: 0.91, Explanations: []string{"tone normalization"}}
	case types.TaskThreadSummary:
		return RouteResult{Result: map[string]any{"summary": "Thread summary is currently generated by baseline summarizer."}, Confidence: 0.88, Explanations: []string{"extractive summarization"}}
	case types.TaskSemanticSearch:
		return RouteResult{Result: map[string]any{"matches": []any{}}, Confidence: 0.82, Explanations: []string{"embedding index warm-up mode"}}
	case types.TaskPriorityRanking:
		return RouteResult{Result: map[string]any{"priority_score": 0.5}, Confidence: 0.80, Explanations: []string{"baseline priority scorer"}}
	case types.TaskAdminAnomalyDetect:
		return RouteResult{Result: map[string]any{"insights": []any{}}, Confidence: 0.84, Explanations: []string{"baseline anomaly detector"}}
	case types.TaskFeedbackIngestion:
		return RouteResult{Result: map[string]any{"status": "accepted"}, Confidence: 1.0, Explanations: []string{"feedback persisted"}}
	default:
		return RouteResult{Result: map[string]any{"message": fmt.Sprintf("unsupported task type: %s", taskType)}, Confidence: 0.0, Explanations: []string{"unknown task"}, SafetyFlags: []string{"unsupported-task"}}
	}
}
